---
title: "Chapter_12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries

```{r message=FALSE, warning=FALSE}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
```

# Load Data

## Create Species List Table 
```{r}
webpage <- read_html("https://www.pwrc.usgs.gov/bbl/manual/speclist.cfm")

tbls <- html_nodes(webpage, "table") %>% 
    html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))
```

## Load Shorebird Data from Arctic Data Center
```{r message=FALSE, warning=FALSE}
predator <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e")

nest <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d")
```

# Function to Add the Species Name

```{r}
codeToName <- function(spCode){
  spCodeJoin<-left_join(spCode, species, by = c("species" = "alpha_code"))
  return(spCodeJoin)
}

#test<-codeToName(predator)
```
```{r}
predatorNames <- codeToName(predator)
nestNames <- codeToName(nest)
```

#Calculate total number of predators by year and species, and plot the result

```{r}
predatorSums <- predatorNames %>%
  select(year, common_name,count) %>%
  group_by(year, common_name) %>%
  summarise(toalPredators = sum(count))
  #arrange(desc(catch_mean))
  

```


