---
title: "Data Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r message=FALSE, warning=FALSE}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(scales) # install.packages("scales")
```

## Load Data

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)

```

## Salmon Data Summary
```{r}
annual_esc <- esc %>%
  separate(sampleDate, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year = as.numeric(year) )%>%
  group_by(year, Species, SASAP.Region)%>%
  summarise(totalCount = sum(DailyCount))%>%
  filter(Species %in% c("Sockeye", "Chum", "Coho", "Chinook", "Pink"))

head(annual_esc)
```

